spring.application.name=bin-monitoring-service
spring.application.name=bin-monitoring-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/eco-clean
spring.datasource.username=root
spring.datasource.password=ramcharan@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true